"""train_efficientnet_multihead.py
Trains EfficientNet-B0 with one regression head per feature to predict
DINO-labeled counts (tree, streetlight, storefront) from day images.

Pipeline:
  1. Reads DINO counts CSV (generated by dino_exps.py on eff-training-upload/)
  2. Loads images from eff-training-upload/
  3. Trains shared backbone + per-feature heads
  4. Saves best model to best_efficientnet_multihead.pt

Run on HPC:
  python3 model-training/train_efficientnet_multihead.py
"""

import pandas as pd
import numpy as np
from pathlib import Path

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from torchvision.models import efficientnet_b0, EfficientNet_B0_Weights
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingLR
from sklearn.model_selection import train_test_split
from tqdm import tqdm

# ── Config ────────────────────────────────────────────────────────────────────
# Path to the DINO counts CSV produced by dino_exps.py
DINO_CSV    = Path("../dino_experiments/dino_counts/dino_efficientnet_train_images.csv")
# Folder containing the resized day images uploaded to HPC
IMAGE_DIR = Path("../urban-mosaic/washington-square")
# Change these to point to the current directory
SAVE_PATH   = Path("best_efficientnet_multihead.pt")
PREDS_DIR   = Path("val_predictions_multihead")

# Column names in the DINO CSV that are regression targets
TARGETS     = ["tree", "streetlight", "storefront"]
# Column in DINO CSV that holds the image filename
IMAGE_COL   = "image"

N_SAMPLES   = None   # None = use all rows
BATCH_SIZE  = 32
NUM_EPOCHS  = 100
LR          = 1e-4
IMG_SIZE    = 512
NUM_WORKERS = 8
VAL_SPLIT   = 0.2
RANDOM_SEED = 42
SAVE_PREDS_EVERY = 5

DEVICE = (
    "cuda" if torch.cuda.is_available()
    else "mps" if torch.backends.mps.is_available()
    else "cpu"
)

# ── Dataset ───────────────────────────────────────────────────────────────────
class CountDataset(Dataset):
    def __init__(self, df, image_dir, targets, transform=None):
        self.df        = df.reset_index(drop=True)
        self.image_dir = Path(image_dir)
        self.targets   = targets
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        from PIL import Image
        row      = self.df.iloc[idx]
        img_path = self.image_dir / row[IMAGE_COL]
        print(f"Processing: {img_path}") # Uncomment this to see the filename
        try:
            image = Image.open(img_path).convert("RGB")
            # Force load to catch truncation errors here instead of later
            image.load() 
        except Exception as e:
            print(f"  Warning: Skipping corrupt image {img_path}: {e}")
            # Create a black dummy image if the file is broken
            image = Image.new("RGB", (IMG_SIZE, IMG_SIZE), (0, 0, 0))

        if self.transform:
            image = self.transform(image)
        
        if image.shape != (3, 512, 512):
            print(f"!!! SHAPE MISMATCH at {img_path}: {image.shape}")
        labels = torch.tensor(row[self.targets].values.astype(np.float32))
        return image, labels

# ── Transforms ────────────────────────────────────────────────────────────────
train_tf = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])

val_tf = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])

# ── Model ─────────────────────────────────────────────────────────────────────
class EfficientNetMultiHead(nn.Module):
    def __init__(self, targets: list):
        super().__init__()
        base = efficientnet_b0(weights=EfficientNet_B0_Weights.IMAGENET1K_V1)
        in_features = base.classifier[1].in_features  # 1280 for b0

        # Shared backbone — all heads learn from the same visual features
        self.backbone = base.features
        self.pool = base.avgpool

        # One independent regression head per target
        self.heads = nn.ModuleDict({
            t: nn.Sequential(
                nn.Dropout(p=0.5),
                nn.Linear(in_features, 128),
                nn.ReLU(),
                nn.Dropout(p=0.3),
                nn.Linear(128, 1),
                nn.ReLU(),  # counts are non-negative
            )
            for t in targets
        })
        self._targets = targets

    def forward(self, x):
        x = torch.flatten(self.pool(self.backbone(x)), 1)  # (batch, 1280)
        return torch.stack([self.heads[t](x).squeeze(1) for t in self._targets], dim=1)

# ── Helpers ───────────────────────────────────────────────────────────────────
def per_target_mae(preds, labels, targets):
    maes = (preds - labels).abs().mean(dim=0)
    return {t: maes[i].item() for i, t in enumerate(targets)}

def save_predictions(val_df, all_preds, targets, epoch):
    PREDS_DIR.mkdir(parents=True, exist_ok=True)
    preds_np = all_preds.numpy()
    out = val_df[[IMAGE_COL] + targets].copy().reset_index(drop=True)
    for i, t in enumerate(targets):
        out[f"pred_{t}"] = preds_np[:, i].round(2)
    out_path = PREDS_DIR / f"val_preds_epoch_{epoch:03d}.csv"
    out.to_csv(out_path, index=False)
    print(f"  Saved val predictions to {out_path}")

# ── Training loop ─────────────────────────────────────────────────────────────
def train():
    torch.cuda.empty_cache()
    df = pd.read_csv(DINO_CSV)
    df[TARGETS] = df[TARGETS].fillna(0)

    # Drop rows whose image file doesn't exist on disk
    df = df[df[IMAGE_COL].apply(lambda f: (IMAGE_DIR / f).exists())].reset_index(drop=True)
    print(f"Images found on disk: {len(df)}")

    if N_SAMPLES and N_SAMPLES < len(df):
        df = df.sample(n=N_SAMPLES, random_state=RANDOM_SEED)

    print("\nLabel stats:")
    print(df[TARGETS].describe().loc[["mean", "std", "max"]])
    print("\n% zeros per target:")
    print(((df[TARGETS] == 0).mean() * 100).round(1).to_string())
    print()

    train_df, val_df = train_test_split(df, test_size=VAL_SPLIT, random_state=RANDOM_SEED)
    print(f"Train: {len(train_df)}  Val: {len(val_df)}")

    train_ds = CountDataset(train_df, IMAGE_DIR, TARGETS, train_tf)
    val_ds   = CountDataset(val_df,   IMAGE_DIR, TARGETS, val_tf)

    train_dl = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,
                          num_workers=NUM_WORKERS, pin_memory=(DEVICE != "cpu"))
    val_dl   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False,
                          num_workers=NUM_WORKERS, pin_memory=(DEVICE != "cpu"))

    model     = EfficientNetMultiHead(targets=TARGETS).to(DEVICE)
    optimizer = AdamW(model.parameters(), lr=LR, weight_decay=1e-3)
    scheduler = CosineAnnealingLR(optimizer, T_max=NUM_EPOCHS)
    criterion = nn.HuberLoss()

    best_val_loss = float("inf")
    log_path = SAVE_PATH.parent / "training_log.csv"
    log_rows  = []
    scaler = torch.amp.GradScaler('cuda')
    for epoch in range(NUM_EPOCHS):
        model.train()
        train_loss = 0.0
        
        # Wrapped with tqdm for progress visibility
        pbar = tqdm(train_dl, desc=f"Epoch {epoch+1}/{NUM_EPOCHS}", unit="batch")
        
        for images, labels in pbar:
            images, labels = images.to(DEVICE), labels.to(DEVICE)
            optimizer.zero_grad()
            
            # Mixed Precision Forward Pass
            with torch.amp.autocast('cuda'):
                preds = model(images)
                loss = criterion(preds, labels)
            
            # Mixed Precision Backward Pass
            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
            
            train_loss += loss.item()
            
            # Optional: Update progress bar with current loss
            pbar.set_postfix(loss=loss.item())

        # Validation Loop remains similar (but use autocast here too!)
        model.eval()
        val_loss, all_preds, all_labels = 0.0, [], []
        with torch.no_grad():
            with torch.amp.autocast('cuda'):
                for images, labels in val_dl:
                    images, labels = images.to(DEVICE), labels.to(DEVICE)
                    preds = model(images)
                    val_loss += criterion(preds, labels).item()
                    all_preds.append(preds.cpu())
                    all_labels.append(labels.cpu())

        train_loss /= len(train_dl)
        val_loss   /= len(val_dl)
        scheduler.step()

        all_preds  = torch.cat(all_preds)
        all_labels = torch.cat(all_labels)
        mae     = per_target_mae(all_preds, all_labels, TARGETS)
        mae_str = "  ".join(f"{t}={v:.2f}" for t, v in mae.items())
        print(f"Epoch {epoch+1:03d}/{NUM_EPOCHS}  train={train_loss:.4f}  val={val_loss:.4f}  MAE: {mae_str}")

        log_rows.append({"epoch": epoch + 1, "train_loss": round(train_loss, 6),
                         "val_loss": round(val_loss, 6), **{f"mae_{k}": round(v, 4) for k, v in mae.items()}})
        pd.DataFrame(log_rows).to_csv(log_path, index=False)

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            SAVE_PATH.parent.mkdir(parents=True, exist_ok=True)
            torch.save(model.state_dict(), SAVE_PATH)
            print(f"  Saved best model to {SAVE_PATH}")

        if (epoch + 1) % SAVE_PREDS_EVERY == 0:
            save_predictions(val_df, all_preds, TARGETS, epoch + 1)

    print(f"\nDone. Best val loss: {best_val_loss:.4f}")


if __name__ == "__main__":
    print(f"Device: {DEVICE}")
    train()
